FROM node:18.17-alpine

# Defina o diretório de trabalho
WORKDIR /app-frontend

# Copie os arquivos de dependência
COPY package*.json ./

# Limpe o cache do NPM e instale as dependências
RUN npm install

# Copie o restante do código da aplicação
COPY . .

# Exponha a porta e defina o comando de início
EXPOSE 3000
CMD ["npm", "run", "dev"]